packages:
  - autumn-js
  - frameworks/*
  - nextjs
  - compose
  - cli
  - atmn
  - ui
  - test-worker
  - next15
  - next-bug
  - vite-spa
  - convex
  - ts-sdk

ignoredBuiltDependencies:
  - better-sqlite3
